
public enum Major {
	SOFTWARE_ENGINEERING,
	MANAGEMENT_TECHNOLOGY,
	FINANCIAL_MATHEMATICS,
	SECURITY_TECHNOLOGY,
	MEDICAL_DEVICE_INNOVATION,
	COMPUTER_SCIENCE,
	ELECTRICAL_ENGINEERING,
	CARDIOLOGY,
	NEUROLOGY,
	PHARMACOLOGY,
	IMMUNOLOGY,
	GRADUATE_SCHOOL_SPECIAL	
}
